version: "3.8"

services:
  nginx:
    restart: on-failure
    image: nginx:1-alpine
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/build
    ports:
      - 5000:80
    depends_on:
      - django

  postgres:
    build:
      dockerfile: postgres.Dockerfile
      context: ./docker
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

  django:
    build:
      dockerfile: docker/django.dev.Dockerfile
      context: .
    restart: always
    # command: gunicorn codeselfstudy.wsgi:application --bind 0.0.0.0:5000
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
      - static_volume:/app/build
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file: .env

  redis:
    image: redis:6-alpine
    command: redis-server
    volumes:
      - "redis:/var/lib/redis/data"
    ports:
      - "6379:6379"

volumes:
  postgres:
  redis:
  static_volume:
