# Generated by Django 3.1.3 on 2020-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Some text about the language for its description page.'),
        ),
    ]
