# Generated by Django 3.1.3 on 2020-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Some markdown text about the language for its description page.'),
        ),
    ]
