# Generated by Django 4.0.3 on 2022-04-11 01:43

from django.db import migrations, models
import django.utils.timezone
import helpers.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Codewars", "Codewars"),
                            ("Leetcode", "Leetcode"),
                            ("Project Euler", "Project Euler"),
                            ("Code Self Study", "Code Self Study"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (0, "Level Unknown"),
                            (1, "Level One"),
                            (2, "Level Two"),
                            (3, "Level Three"),
                            (4, "Level Four"),
                        ],
                        default=0,
                    ),
                ),
                ("unsafe_description", models.TextField()),
                (
                    "cooked_description",
                    models.TextField(help_text="The description of the puzzle"),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=helpers.utils.create_random_slug, max_length=255
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        blank=True,
                        help_text="If the puzzle originated somewhere else, put the full URL here",
                        null=True,
                    ),
                ),
                (
                    "original_raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Any Python data type here will be turned into JSONB.",
                    ),
                ),
                (
                    "was_seen",
                    models.BooleanField(
                        default=False,
                        help_text="Has the puzzle been posted to Slack before?",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
