# Generated by Django 3.1.3 on 2020-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Level Unknown'), (1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five'), (6, 'Level Six'), (7, 'Level Seven'), (8, 'Level Eight'), (9, 'Level Nine'), (10, 'Level Ten')], default=0),
        ),
    ]
