# Generated by Django 3.1.3 on 2020-11-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20201121_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='tags',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='original_raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any Python data type here will be turned into JSONB.'),
        ),
    ]
