# Generated by Django 3.1.3 on 2020-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_auto_20201122_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='was_seen',
            field=models.BooleanField(default=False, help_text='Has the puzzle been posted to Slack before?'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Level Unknown'), (1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four')], default=0),
        ),
    ]
